"""took out end_date from lessons

Revision ID: 1bd334912fb3
Revises: b868ffe6e53d
Create Date: 2018-11-06 10:35:08.807966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd334912fb3'
down_revision = 'b868ffe6e53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('end_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
