"""changed invoice_date col

Revision ID: 372596e5af49
Revises: af3e1959d978
Create Date: 2018-10-19 10:24:39.618080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372596e5af49'
down_revision = 'af3e1959d978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'home_phone')
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.add_column('accounts', sa.Column('home_phone', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
