"""oops

Revision ID: 685bae9a84af
Revises: 
Create Date: 2018-10-24 12:04:21.843476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685bae9a84af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name1', sa.String(length=50), nullable=True),
    sa.Column('l_name1', sa.String(length=50), nullable=True),
    sa.Column('cell_phone1', sa.String(length=10), nullable=True),
    sa.Column('email1', sa.String(length=120), nullable=True),
    sa.Column('home_phone1', sa.String(length=10), nullable=True),
    sa.Column('f_name2', sa.String(length=50), nullable=True),
    sa.Column('l_name2', sa.String(length=50), nullable=True),
    sa.Column('cell_phone2', sa.String(length=10), nullable=True),
    sa.Column('email2', sa.String(length=120), nullable=True),
    sa.Column('account_bal', sa.Float(precision=10), nullable=True),
    sa.Column('account_credit', sa.Float(precision=10), nullable=True),
    sa.Column('home_phone2', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_num', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipcode', sa.String(length=5), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_username'), 'teachers', ['username'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('invoice_total', sa.Float(precision=10), nullable=True),
    sa.Column('payment_total', sa.Float(precision=10), nullable=True),
    sa.Column('invoice_due_date', sa.DateTime(timezone=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=50), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_ID', sa.Integer(), nullable=True),
    sa.Column('teacher_ID', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['account_ID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['teacher_ID'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_ID', sa.Integer(), nullable=True),
    sa.Column('account_ID', sa.Integer(), nullable=True),
    sa.Column('was_present', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_ID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['student_ID'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendence_was_present'), 'attendence', ['was_present'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendence_was_present'), table_name='attendence')
    op.drop_table('attendence')
    op.drop_table('students')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_teachers_username'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('instruments')
    op.drop_table('accounts')
    # ### end Alembic commands ###
