"""changed Lessons and Recurring_pattern tables for RRULES

Revision ID: 6c20297dd1d1
Revises: 1bd334912fb3
Create Date: 2018-11-08 13:33:04.472435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c20297dd1d1'
down_revision = '1bd334912fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('end_time', sa.String(length=10), nullable=True))
    op.drop_column('recurring_pattern', 'week_of_month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_pattern', sa.Column('week_of_month', sa.INTEGER(), nullable=True))
    op.drop_column('lessons', 'end_time')
    # ### end Alembic commands ###
