"""renamed all cols in accounts, also corrected a spelling error

Revision ID: 8a475f29c241
Revises: 685bae9a84af
Create Date: 2018-11-01 17:51:18.395637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a475f29c241'
down_revision = '685bae9a84af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_ID', sa.Integer(), nullable=True),
    sa.Column('account_ID', sa.Integer(), nullable=True),
    sa.Column('was_present', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_ID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['student_ID'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_was_present'), 'attendance', ['was_present'], unique=False)
    op.drop_index('ix_attendence_was_present', table_name='attendence')
    op.drop_table('attendence')
    op.add_column('accounts', sa.Column('primary_cell_phone', sa.String(length=10), nullable=True))
    op.add_column('accounts', sa.Column('primary_email', sa.String(length=120), nullable=True))
    op.add_column('accounts', sa.Column('primary_fname', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('primary_home_phone', sa.String(length=10), nullable=True))
    op.add_column('accounts', sa.Column('primary_lname', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('secondary_cell_phone', sa.String(length=10), nullable=True))
    op.add_column('accounts', sa.Column('secondary_email', sa.String(length=120), nullable=True))
    op.add_column('accounts', sa.Column('secondary_fname', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('secondary_home_phone', sa.String(length=10), nullable=True))
    op.add_column('accounts', sa.Column('secondary_lname', sa.String(length=50), nullable=True))
    op.drop_column('accounts', 'cell_phone1')
    op.drop_column('accounts', 'home_phone1')
    op.drop_column('accounts', 'l_name2')
    op.drop_column('accounts', 'home_phone2')
    op.drop_column('accounts', 'l_name1')
    op.drop_column('accounts', 'f_name1')
    op.drop_column('accounts', 'f_name2')
    op.drop_column('accounts', 'email2')
    op.drop_column('accounts', 'cell_phone2')
    op.drop_column('accounts', 'email1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email1', sa.VARCHAR(length=120), nullable=True))
    op.add_column('accounts', sa.Column('cell_phone2', sa.VARCHAR(length=10), nullable=True))
    op.add_column('accounts', sa.Column('email2', sa.VARCHAR(length=120), nullable=True))
    op.add_column('accounts', sa.Column('f_name2', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('f_name1', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('l_name1', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('home_phone2', sa.VARCHAR(length=10), nullable=True))
    op.add_column('accounts', sa.Column('l_name2', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('home_phone1', sa.VARCHAR(length=10), nullable=True))
    op.add_column('accounts', sa.Column('cell_phone1', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('accounts', 'secondary_lname')
    op.drop_column('accounts', 'secondary_home_phone')
    op.drop_column('accounts', 'secondary_fname')
    op.drop_column('accounts', 'secondary_email')
    op.drop_column('accounts', 'secondary_cell_phone')
    op.drop_column('accounts', 'primary_lname')
    op.drop_column('accounts', 'primary_home_phone')
    op.drop_column('accounts', 'primary_fname')
    op.drop_column('accounts', 'primary_email')
    op.drop_column('accounts', 'primary_cell_phone')
    op.create_table('attendence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_ID', sa.INTEGER(), nullable=True),
    sa.Column('account_ID', sa.INTEGER(), nullable=True),
    sa.Column('was_present', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_ID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['student_ID'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendence_was_present', 'attendence', ['was_present'], unique=False)
    op.drop_index(op.f('ix_attendance_was_present'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
