"""added week_days model, changed recurring_pattern day_of_week to foreign key

Revision ID: 8ad09c2077c0
Revises: f0f11edc2ce3
Create Date: 2018-11-08 13:49:27.483880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad09c2077c0'
down_revision = 'f0f11edc2ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recurring_pattern', sa.Column('day_of_week_ID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recurring_pattern', 'week_days', ['day_of_week_ID'], ['id'])
    op.drop_column('recurring_pattern', 'week_of_month')
    op.drop_column('recurring_pattern', 'separation_count')
    op.drop_column('recurring_pattern', 'day_of_week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_pattern', sa.Column('day_of_week', sa.INTEGER(), nullable=True))
    op.add_column('recurring_pattern', sa.Column('separation_count', sa.INTEGER(), nullable=True))
    op.add_column('recurring_pattern', sa.Column('week_of_month', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recurring_pattern', type_='foreignkey')
    op.drop_column('recurring_pattern', 'day_of_week_ID')
    op.drop_table('week_days')
    # ### end Alembic commands ###
