"""deleted Students.attendence_ID

Revision ID: a0440fbd1613
Revises: cd7eefddcea5
Create Date: 2018-10-23 11:31:43.903349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0440fbd1613'
down_revision = 'cd7eefddcea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'home_phone')
    op.create_index(op.f('ix_attendence_was_present'), 'attendence', ['was_present'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'attendence_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('attendence_ID', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'students', 'attendence', ['attendence_ID'], ['id'])
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_attendence_was_present'), table_name='attendence')
    op.add_column('accounts', sa.Column('home_phone', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
