"""adding contactType table

Revision ID: aaf8cdf5fcde
Revises: 8afe40d5eec9
Create Date: 2019-10-18 19:55:28.144881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf8cdf5fcde'
down_revision = '8afe40d5eec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contactType', sa.String(length=50), nullable=True),
    sa.Column('cancelled_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_type')
    # ### end Alembic commands ###
