"""added communication tables... hopefully correctly

Revision ID: b2173145fb66
Revises: 7777e90e9833
Create Date: 2019-10-20 18:04:54.461214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2173145fb66'
down_revision = '7777e90e9833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communication_type', sa.String(length=50), nullable=True),
    sa.Column('cancelled_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communication_type_ID', sa.Integer(), nullable=True),
    sa.Column('communication_data', sa.String(length=120), nullable=True),
    sa.Column('cancelled_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['communication_type_ID'], ['communication_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkingContactCommunication',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'communication_id')
    )
    op.add_column('contact', sa.Column('contact_type_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'contact_type', ['contact_type_id'], ['id'])
    op.drop_column('contact', 'contact_type_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('contact_type_ID', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'contact_type', ['contact_type_ID'], ['id'])
    op.drop_column('contact', 'contact_type_id')
    op.drop_table('linkingContactCommunication')
    op.drop_table('communication')
    op.drop_table('communication_type')
    # ### end Alembic commands ###
