"""changed attendence.was_present col

Revision ID: bc81e700e5c9
Revises: ff1e89de7a42
Create Date: 2018-10-19 10:53:19.906617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc81e700e5c9'
down_revision = 'ff1e89de7a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'home_phone')
    op.create_index(op.f('ix_attendence_was_present'), 'attendence', ['was_present'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_attendence_was_present'), table_name='attendence')
    op.add_column('accounts', sa.Column('home_phone', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
