"""fixed a cool typo

Revision ID: cbd9eeb35179
Revises: f5ad39d83974
Create Date: 2018-09-28 20:24:51.877410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd9eeb35179'
down_revision = 'f5ad39d83974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('f_name1', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('f_name2', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('l_name1', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('l_name2', sa.String(length=50), nullable=True))
    op.drop_column('accounts', 'L_name1')
    op.drop_column('accounts', 'F_name2')
    op.drop_column('accounts', 'F_name1')
    op.drop_column('accounts', 'L_name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('L_name2', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('F_name1', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('F_name2', sa.VARCHAR(length=50), nullable=True))
    op.add_column('accounts', sa.Column('L_name1', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('accounts', 'l_name2')
    op.drop_column('accounts', 'l_name1')
    op.drop_column('accounts', 'f_name2')
    op.drop_column('accounts', 'f_name1')
    # ### end Alembic commands ###
