"""added home_phone1 and 2 - accounts

Revision ID: d95b8c587fce
Revises: de31ceb7cfd6
Create Date: 2018-10-02 12:58:20.164095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95b8c587fce'
down_revision = 'de31ceb7cfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('home_phone1', sa.String(length=10), nullable=True))
    op.add_column('accounts', sa.Column('home_phone2', sa.String(length=10), nullable=True))
    op.drop_column('accounts', 'home_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('home_phone', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('accounts', 'home_phone2')
    op.drop_column('accounts', 'home_phone1')
    # ### end Alembic commands ###
