"""Added separation_count to Recurring_pattern again

Revision ID: e94d143c95b1
Revises: 7aeadb9cef31
Create Date: 2018-11-09 12:11:34.933169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94d143c95b1'
down_revision = '7aeadb9cef31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_pattern', sa.Column('separation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_pattern', 'separation_count')
    # ### end Alembic commands ###
