"""

Revision ID: f0f11edc2ce3
Revises: 6c20297dd1d1
Create Date: 2018-11-08 13:40:04.191168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f11edc2ce3'
down_revision = '6c20297dd1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_pattern', 'week_of_month')
    op.drop_column('recurring_pattern', 'separation_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_pattern', sa.Column('separation_count', sa.INTEGER(), nullable=True))
    op.add_column('recurring_pattern', sa.Column('week_of_month', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
